#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CarShare.Resource", IsApplication=true)]

namespace CarShare
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_in_right = global::CarShare.Resource.Animation.slide_in_right;
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_out_left = global::CarShare.Resource.Animation.slide_out_left;
			global::Xamarin.Auth._MobileServices.Resource.Drawable.ic_arrow_back = global::CarShare.Resource.Drawable.ic_arrow_back;
			global::Xamarin.Auth._MobileServices.Resource.Id.webview = global::CarShare.Resource.Id.webview;
			global::Xamarin.Auth._MobileServices.Resource.Layout.activity_webview = global::CarShare.Resource.Layout.activity_webview;
			global::Xamarin.Auth._MobileServices.Resource.String.ApplicationName = global::CarShare.Resource.String.ApplicationName;
			global::Xamarin.Auth._MobileServices.Resource.String.Hello = global::CarShare.Resource.String.Hello;
			global::Xamarin.Auth._MobileServices.Resource.String.title_activity_webview = global::CarShare.Resource.String.title_activity_webview;
			global::PCLCrypto.Resource.String.ApplicationName = global::CarShare.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::CarShare.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_left = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0c0002
			public const int county = 2131492866;
			
			// aapt resource value: 0x7f0c0000
			public const int gender = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int passengersNumber = 2131492865;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f01001a
			public const int buttonSize = 2130771994;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010012
			public const int cameraMaxZoomPreference = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int cameraMinZoomPreference = 2130771985;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010019
			public const int circleCrop = 2130771993;
			
			// aapt resource value: 0x7f01001b
			public const int colorScheme = 2130771995;
			
			// aapt resource value: 0x7f010024
			public const int font = 2130772004;
			
			// aapt resource value: 0x7f01001d
			public const int fontProviderAuthority = 2130771997;
			
			// aapt resource value: 0x7f010020
			public const int fontProviderCerts = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int fontProviderFetchStrategy = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int fontProviderFetchTimeout = 2130772002;
			
			// aapt resource value: 0x7f01001e
			public const int fontProviderPackage = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int fontProviderQuery = 2130771999;
			
			// aapt resource value: 0x7f010023
			public const int fontStyle = 2130772003;
			
			// aapt resource value: 0x7f010025
			public const int fontWeight = 2130772005;
			
			// aapt resource value: 0x7f010018
			public const int imageAspectRatio = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int imageAspectRatioAdjust = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int latLngBoundsNorthEastLatitude = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int latLngBoundsNorthEastLongitude = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int latLngBoundsSouthWestLatitude = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int latLngBoundsSouthWestLongitude = 2130771988;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f01001c
			public const int scopeUris = 2130771996;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090000
			public const int abc_action_bar_embed_tabs = 2131296256;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f07000f
			public const int common_google_signin_btn_text_dark = 2131165199;
			
			// aapt resource value: 0x7f070000
			public const int common_google_signin_btn_text_dark_default = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int common_google_signin_btn_text_dark_disabled = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int common_google_signin_btn_text_dark_focused = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int common_google_signin_btn_text_dark_pressed = 2131165187;
			
			// aapt resource value: 0x7f070010
			public const int common_google_signin_btn_text_light = 2131165200;
			
			// aapt resource value: 0x7f070004
			public const int common_google_signin_btn_text_light_default = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int common_google_signin_btn_text_light_disabled = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int common_google_signin_btn_text_light_focused = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int common_google_signin_btn_text_light_pressed = 2131165191;
			
			// aapt resource value: 0x7f070011
			public const int common_google_signin_btn_tint = 2131165201;
			
			// aapt resource value: 0x7f07000b
			public const int notification_action_color_filter = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int notification_icon_bg_color = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int notification_material_background_media_default_color = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int primary_text_default_material_dark = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int ripple_material_light = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int secondary_text_default_material_dark = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int secondary_text_default_material_light = 2131165198;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0004
			public const int compat_button_inset_horizontal_material = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int compat_button_inset_vertical_material = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int compat_button_padding_horizontal_material = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int compat_button_padding_vertical_material = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int compat_control_corner_material = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int notification_action_icon_size = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int notification_action_text_size = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int notification_big_circle_margin = 2131361803;
			
			// aapt resource value: 0x7f0a0001
			public const int notification_content_margin_start = 2131361793;
			
			// aapt resource value: 0x7f0a000c
			public const int notification_large_icon_height = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int notification_large_icon_width = 2131361805;
			
			// aapt resource value: 0x7f0a0002
			public const int notification_main_column_padding_top = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int notification_media_narrow_margin = 2131361795;
			
			// aapt resource value: 0x7f0a000e
			public const int notification_right_icon_size = 2131361806;
			
			// aapt resource value: 0x7f0a0000
			public const int notification_right_side_padding_top = 2131361792;
			
			// aapt resource value: 0x7f0a000f
			public const int notification_small_icon_background_padding = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int notification_small_icon_size_as_large = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int notification_subtext_size = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int notification_top_pad = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int notification_top_pad_large_text = 2131361811;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_focused = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_disabled = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_focused = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_text_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_normal_background = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_disabled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_normal_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int googleg_disabled_color_18 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int googleg_standard_color_18 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_arrow_back = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int notification_action_background = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int notification_bg = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int notification_bg_low = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int notification_bg_low_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int notification_bg_low_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int notification_bg_normal = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int notification_bg_normal_pressed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int notification_icon_background = 2130837533;
			
			// aapt resource value: 0x7f020020
			public const int notification_template_icon_bg = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int notification_template_icon_low_bg = 2130837537;
			
			// aapt resource value: 0x7f02001e
			public const int notification_tile_bg = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int notify_panel_notification_icon_bg = 2130837535;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0017
			public const int ApplicantAccept = 2131427351;
			
			// aapt resource value: 0x7f0b0018
			public const int ApplicantRefuse = 2131427352;
			
			// aapt resource value: 0x7f0b004e
			public const int action0 = 2131427406;
			
			// aapt resource value: 0x7f0b004b
			public const int action_container = 2131427403;
			
			// aapt resource value: 0x7f0b0052
			public const int action_divider = 2131427410;
			
			// aapt resource value: 0x7f0b004c
			public const int action_image = 2131427404;
			
			// aapt resource value: 0x7f0b004d
			public const int action_text = 2131427405;
			
			// aapt resource value: 0x7f0b005c
			public const int actions = 2131427420;
			
			// aapt resource value: 0x7f0b000a
			public const int adjust_height = 2131427338;
			
			// aapt resource value: 0x7f0b000b
			public const int adjust_width = 2131427339;
			
			// aapt resource value: 0x7f0b0012
			public const int async = 2131427346;
			
			// aapt resource value: 0x7f0b000f
			public const int auto = 2131427343;
			
			// aapt resource value: 0x7f0b0013
			public const int blocking = 2131427347;
			
			// aapt resource value: 0x7f0b002e
			public const int buttonAddDates = 2131427374;
			
			// aapt resource value: 0x7f0b0043
			public const int buttonDriverCompletedJourney = 2131427395;
			
			// aapt resource value: 0x7f0b0042
			public const int buttonDriverCreateJourney = 2131427394;
			
			// aapt resource value: 0x7f0b0032
			public const int buttonDriverJourneyBack = 2131427378;
			
			// aapt resource value: 0x7f0b0035
			public const int buttonDriverOldJourneyBack = 2131427381;
			
			// aapt resource value: 0x7f0b0041
			public const int buttonDriverUpcomingJourney = 2131427393;
			
			// aapt resource value: 0x7f0b001b
			public const int buttonFindMe = 2131427355;
			
			// aapt resource value: 0x7f0b004a
			public const int buttonLogOut = 2131427402;
			
			// aapt resource value: 0x7f0b0047
			public const int buttonPassengerCompletedJourney = 2131427399;
			
			// aapt resource value: 0x7f0b008f
			public const int buttonPassengerJourneyBack = 2131427471;
			
			// aapt resource value: 0x7f0b008c
			public const int buttonPassengerOldJourneyBack = 2131427468;
			
			// aapt resource value: 0x7f0b0046
			public const int buttonPassengerSearchJourney = 2131427398;
			
			// aapt resource value: 0x7f0b0045
			public const int buttonPassengerUpcomingJourneys = 2131427397;
			
			// aapt resource value: 0x7f0b001e
			public const int buttonSave = 2131427358;
			
			// aapt resource value: 0x7f0b006c
			public const int buttonSearchJourneyMyLocation = 2131427436;
			
			// aapt resource value: 0x7f0b0080
			public const int buttonSearchJourneyResultsBack = 2131427456;
			
			// aapt resource value: 0x7f0b006f
			public const int buttonSearchJourneySearch = 2131427439;
			
			// aapt resource value: 0x7f0b0071
			public const int buttonSearchJourneySelectDate = 2131427441;
			
			// aapt resource value: 0x7f0b0073
			public const int buttonSearchJourneySelectTime = 2131427443;
			
			// aapt resource value: 0x7f0b006e
			public const int buttonSearchJourneySetTo = 2131427438;
			
			// aapt resource value: 0x7f0b001c
			public const int buttonSetFrom = 2131427356;
			
			// aapt resource value: 0x7f0b006d
			public const int buttonSetSearchJourneySetFrom = 2131427437;
			
			// aapt resource value: 0x7f0b001d
			public const int buttonSetTo = 2131427357;
			
			// aapt resource value: 0x7f0b0088
			public const int buttonShowJourneyApplicants = 2131427464;
			
			// aapt resource value: 0x7f0b004f
			public const int cancel_action = 2131427407;
			
			// aapt resource value: 0x7f0b0057
			public const int chronometer = 2131427415;
			
			// aapt resource value: 0x7f0b0065
			public const int county = 2131427429;
			
			// aapt resource value: 0x7f0b0010
			public const int dark = 2131427344;
			
			// aapt resource value: 0x7f0b0062
			public const int email = 2131427426;
			
			// aapt resource value: 0x7f0b005e
			public const int end_padder = 2131427422;
			
			// aapt resource value: 0x7f0b0060
			public const int firstName = 2131427424;
			
			// aapt resource value: 0x7f0b0014
			public const int forever = 2131427348;
			
			// aapt resource value: 0x7f0b0064
			public const int gender = 2131427428;
			
			// aapt resource value: 0x7f0b0005
			public const int hybrid = 2131427333;
			
			// aapt resource value: 0x7f0b0059
			public const int icon = 2131427417;
			
			// aapt resource value: 0x7f0b005d
			public const int icon_group = 2131427421;
			
			// aapt resource value: 0x7f0b000c
			public const int icon_only = 2131427340;
			
			// aapt resource value: 0x7f0b003f
			public const int imageViewProfilePic = 2131427391;
			
			// aapt resource value: 0x7f0b0058
			public const int info = 2131427416;
			
			// aapt resource value: 0x7f0b0015
			public const int italic = 2131427349;
			
			// aapt resource value: 0x7f0b0061
			public const int lastName = 2131427425;
			
			// aapt resource value: 0x7f0b0011
			public const int light = 2131427345;
			
			// aapt resource value: 0x7f0b0000
			public const int line1 = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int line3 = 2131427329;
			
			// aapt resource value: 0x7f0b001a
			public const int linearLayout1 = 2131427354;
			
			// aapt resource value: 0x7f0b0020
			public const int linearLayout2 = 2131427360;
			
			// aapt resource value: 0x7f0b0023
			public const int linearLayout3 = 2131427363;
			
			// aapt resource value: 0x7f0b0049
			public const int linearLayout4 = 2131427401;
			
			// aapt resource value: 0x7f0b0029
			public const int linearLayout5 = 2131427369;
			
			// aapt resource value: 0x7f0b001f
			public const int linearLayout6 = 2131427359;
			
			// aapt resource value: 0x7f0b0026
			public const int linearLayout7 = 2131427366;
			
			// aapt resource value: 0x7f0b002d
			public const int linearLayout8 = 2131427373;
			
			// aapt resource value: 0x7f0b0079
			public const int linearLayout9 = 2131427449;
			
			// aapt resource value: 0x7f0b0034
			public const int listViewOldDriverJourneys = 2131427380;
			
			// aapt resource value: 0x7f0b008e
			public const int listViewPassengerJourney = 2131427470;
			
			// aapt resource value: 0x7f0b008b
			public const int listViewPassengerOldJourney = 2131427467;
			
			// aapt resource value: 0x7f0b007f
			public const int listViewSearchJourneyResults = 2131427455;
			
			// aapt resource value: 0x7f0b0089
			public const int listViewShowJourneyApplicants = 2131427465;
			
			// aapt resource value: 0x7f0b0087
			public const int listViewShowJourneyPassengers = 2131427463;
			
			// aapt resource value: 0x7f0b0031
			public const int listViewUpcomingJourneys = 2131427377;
			
			// aapt resource value: 0x7f0b003b
			public const int loginButton = 2131427387;
			
			// aapt resource value: 0x7f0b0019
			public const int mapFrame = 2131427353;
			
			// aapt resource value: 0x7f0b006b
			public const int mapFrameSearch = 2131427435;
			
			// aapt resource value: 0x7f0b0081
			public const int mapFrameShowJourney = 2131427457;
			
			// aapt resource value: 0x7f0b0051
			public const int media_actions = 2131427409;
			
			// aapt resource value: 0x7f0b0006
			public const int none = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int normal = 2131427335;
			
			// aapt resource value: 0x7f0b005b
			public const int notification_background = 2131427419;
			
			// aapt resource value: 0x7f0b0054
			public const int notification_main_column = 2131427412;
			
			// aapt resource value: 0x7f0b0053
			public const int notification_main_column_container = 2131427411;
			
			// aapt resource value: 0x7f0b003a
			public const int passwordInput = 2131427386;
			
			// aapt resource value: 0x7f0b0068
			public const int passwordInput1 = 2131427432;
			
			// aapt resource value: 0x7f0b0069
			public const int passwordInput2 = 2131427433;
			
			// aapt resource value: 0x7f0b0063
			public const int phoneNo = 2131427427;
			
			// aapt resource value: 0x7f0b0036
			public const int pop_button1 = 2131427382;
			
			// aapt resource value: 0x7f0b0037
			public const int pop_button2 = 2131427383;
			
			// aapt resource value: 0x7f0b007c
			public const int pop_buttonSearchApply = 2131427452;
			
			// aapt resource value: 0x7f0b007d
			public const int pop_buttonSearchView = 2131427453;
			
			// aapt resource value: 0x7f0b002b
			public const int radioNo = 2131427371;
			
			// aapt resource value: 0x7f0b0076
			public const int radioSearchJourneyAfter = 2131427446;
			
			// aapt resource value: 0x7f0b0077
			public const int radioSearchJourneyAround = 2131427447;
			
			// aapt resource value: 0x7f0b0075
			public const int radioSearchJourneyBefore = 2131427445;
			
			// aapt resource value: 0x7f0b002c
			public const int radioYes = 2131427372;
			
			// aapt resource value: 0x7f0b003c
			public const int registerButton = 2131427388;
			
			// aapt resource value: 0x7f0b005a
			public const int right_icon = 2131427418;
			
			// aapt resource value: 0x7f0b0055
			public const int right_side = 2131427413;
			
			// aapt resource value: 0x7f0b0008
			public const int satellite = 2131427336;
			
			// aapt resource value: 0x7f0b007b
			public const int seekBarSearchRange = 2131427451;
			
			// aapt resource value: 0x7f0b0025
			public const int selectDateButton = 2131427365;
			
			// aapt resource value: 0x7f0b0022
			public const int spinnerNumOfPassengers = 2131427362;
			
			// aapt resource value: 0x7f0b000d
			public const int standard = 2131427341;
			
			// aapt resource value: 0x7f0b0050
			public const int status_bar_latest_event_content = 2131427408;
			
			// aapt resource value: 0x7f0b0009
			public const int terrain = 2131427337;
			
			// aapt resource value: 0x7f0b003d
			public const int testButton = 2131427389;
			
			// aapt resource value: 0x7f0b0002
			public const int text = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int text2 = 2131427331;
			
			// aapt resource value: 0x7f0b0038
			public const int textLogin = 2131427384;
			
			// aapt resource value: 0x7f0b005f
			public const int textRegister = 2131427423;
			
			// aapt resource value: 0x7f0b0024
			public const int textViewDepDate = 2131427364;
			
			// aapt resource value: 0x7f0b0027
			public const int textViewDepTime = 2131427367;
			
			// aapt resource value: 0x7f0b0030
			public const int textViewDriverJourneyPageTitle = 2131427376;
			
			// aapt resource value: 0x7f0b0033
			public const int textViewDriverOldJourneyPageTitle = 2131427379;
			
			// aapt resource value: 0x7f0b0040
			public const int textViewDriverOptions = 2131427392;
			
			// aapt resource value: 0x7f0b002f
			public const int textViewExtraDates = 2131427375;
			
			// aapt resource value: 0x7f0b0021
			public const int textViewNumOfPassengers = 2131427361;
			
			// aapt resource value: 0x7f0b0048
			public const int textViewOther = 2131427400;
			
			// aapt resource value: 0x7f0b008d
			public const int textViewPassengerJourneyPageTitle = 2131427469;
			
			// aapt resource value: 0x7f0b008a
			public const int textViewPassengerOldJourneyPageTitle = 2131427466;
			
			// aapt resource value: 0x7f0b0044
			public const int textViewPassengerOptions = 2131427396;
			
			// aapt resource value: 0x7f0b002a
			public const int textViewReccuring = 2131427370;
			
			// aapt resource value: 0x7f0b0070
			public const int textViewSearchJourneyDepDate = 2131427440;
			
			// aapt resource value: 0x7f0b0072
			public const int textViewSearchJourneyDepTime = 2131427442;
			
			// aapt resource value: 0x7f0b007e
			public const int textViewSearchJourneyResultsPageTitle = 2131427454;
			
			// aapt resource value: 0x7f0b0074
			public const int textViewSearchJourneyToggleTime = 2131427444;
			
			// aapt resource value: 0x7f0b0078
			public const int textViewSearchLabelRange = 2131427448;
			
			// aapt resource value: 0x7f0b007a
			public const int textViewSearchRange = 2131427450;
			
			// aapt resource value: 0x7f0b0084
			public const int textViewShowJourneyDate = 2131427460;
			
			// aapt resource value: 0x7f0b0082
			public const int textViewShowJourneyFrom = 2131427458;
			
			// aapt resource value: 0x7f0b0085
			public const int textViewShowJourneyTime = 2131427461;
			
			// aapt resource value: 0x7f0b0083
			public const int textViewShowJourneyTo = 2131427459;
			
			// aapt resource value: 0x7f0b0086
			public const int textViewShowPassengerNumbers = 2131427462;
			
			// aapt resource value: 0x7f0b003e
			public const int textViewWelcome = 2131427390;
			
			// aapt resource value: 0x7f0b0056
			public const int time = 2131427414;
			
			// aapt resource value: 0x7f0b0028
			public const int timeSelectButton = 2131427368;
			
			// aapt resource value: 0x7f0b0004
			public const int title = 2131427332;
			
			// aapt resource value: 0x7f0b006a
			public const int tryRegisterButton = 2131427434;
			
			// aapt resource value: 0x7f0b0066
			public const int trySaveButton = 2131427430;
			
			// aapt resource value: 0x7f0b0039
			public const int username = 2131427385;
			
			// aapt resource value: 0x7f0b0067
			public const int usernameReg = 2131427431;
			
			// aapt resource value: 0x7f0b0016
			public const int webview = 2131427350;
			
			// aapt resource value: 0x7f0b000e
			public const int wide = 2131427342;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050001
			public const int cancel_button_image_alpha = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int status_bar_notification_info_maxnum = 2131034114;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_webview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ApplicantsMenu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CreateJourney = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DriverJourneys = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DriversOldJourneys = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int JourneyMenu = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MainProfile = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_action = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_action_tombstone = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_media_action = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_media_cancel_action = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_template_big_media = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_template_big_media_custom = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_template_big_media_narrow = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int notification_template_big_media_narrow_custom = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int notification_template_custom_big = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int notification_template_icon_group = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int notification_template_lines_media = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int notification_template_media = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int notification_template_media_custom = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int notification_template_part_chronometer = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int notification_template_part_time = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int ProfileSetUp = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int Register = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int SearchJourney = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int SearchJourneyMenu = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int SearchJourneysResults = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int ShowJourney = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int ViewOldPassengerJourneys = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int ViewUpcomingPassengerJourneys = 2130903070;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060013
			public const int ApplicationName = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int Hello = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int app_name = 2131099669;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_enable_button = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_enable_text = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_enable_title = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_install_button = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_install_text = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_install_title = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_notification_ticker = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_unknown_issue = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_unsupported_text = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_update_button = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_update_text = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_update_title = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_updating_text = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_wear_update_text = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int common_open_on_phone = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int common_signin_button_text = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int common_signin_button_text_long = 2131099664;
			
			// aapt resource value: 0x7f060017
			public const int county_prompt = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int gender_prompt = 2131099670;
			
			// aapt resource value: 0x7f060011
			public const int status_bar_notification_info_overflow = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int title_activity_webview = 2131099668;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080005
			public const int TextAppearance_Compat_Notification = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int TextAppearance_Compat_Notification_Info = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131230720;
			
			// aapt resource value: 0x7f08000b
			public const int TextAppearance_Compat_Notification_Line2 = 2131230731;
			
			// aapt resource value: 0x7f080004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int TextAppearance_Compat_Notification_Media = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int TextAppearance_Compat_Notification_Time = 2131230727;
			
			// aapt resource value: 0x7f080002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131230722;
			
			// aapt resource value: 0x7f080008
			public const int TextAppearance_Compat_Notification_Title = 2131230728;
			
			// aapt resource value: 0x7f080003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131230723;
			
			// aapt resource value: 0x7f080009
			public const int Widget_Compat_NotificationActionContainer = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int Widget_Compat_NotificationActionText = 2131230730;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130772003,
					2130772004,
					2130772005};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 18
			public const int MapAttrs_cameraMaxZoomPreference = 18;
			
			// aapt resource value: 17
			public const int MapAttrs_cameraMinZoomPreference = 17;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 21
			public const int MapAttrs_latLngBoundsNorthEastLatitude = 21;
			
			// aapt resource value: 22
			public const int MapAttrs_latLngBoundsNorthEastLongitude = 22;
			
			// aapt resource value: 19
			public const int MapAttrs_latLngBoundsSouthWestLatitude = 19;
			
			// aapt resource value: 20
			public const int MapAttrs_latLngBoundsSouthWestLongitude = 20;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
